### ISSUE TITLE
It does not draw the pieChart on Android Nexus 5, with the code I downloaded by the zip.

### ISSUE THREAD

**Issue by alin-rosu** [Ken-Yang/AndroidPieChart#2]
I tried the example app, but I had to change the arrayList from <Float> toi <PieChartData>.
This is the code that I use for the piechart:

xml: 

 <net.kenyang.piechart.PieChart
        android:id="@+id/pieChart"
        android:layout_below="@id/id_bar"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    </net.kenyang.piechart.PieChart>

code:
  ArrayList<PieChartData> alPercentage = new ArrayList<PieChartData>();
        alPercentage.add(new PieChartData(55.0f, "1"));
        alPercentage.add(new PieChartData(45.0f, "2"));
        try {
            // setting data
            pieChart.setAdapter(alPercentage);
            // setting a listener
            pieChart.setOnSelectedListener(new PieChart.OnSelectedLisenter() {
                @Override
                public void onSelected(int iSelectedIndex) {
                    Toast.makeText(PSTravelStatisticsActivity.this, "Select index:" + iSelectedIndex, Toast.LENGTH_SHORT).show();
                }
            });
        } catch (Exception e) {
            Log.i("","error is : " + e.getMessage());
            if (e.getMessage().equals(PieChart.ERROR_NOT_EQUAL_TO_100)){
                Log.e("kenyang", "percentage is not equal to 100");
            }
        }

Also I've included hardware_Accelerated in android manifest as TRUE.
Now I changed the values to not be 100, and then it throws the error that its not equal to.
Like this is just shows me 2 logs, and it stops, and the piechart doesn't appear:

10-08 15:56:45.776  11445-11445/nl.hgrams.passenger I/net.kenyang.piechart.PieChart﹕ PieChart init
10-08 15:56:45.816  11445-11445/nl.hgrams.passenger I/net.kenyang.piechart.PieChart﹕ onDraw

Any ideea how I can fix this? Also I couldn't set the project as a library, being AndroidStudio, so I just set your package into my java folder.

**Comment by Ken-Yang** [comment]
Hi alin-rosu ,

I'm sorry.
i am still refining it. Could you give me a couple days?
It is almost done.
I will update the readme asap.
